version: '3.8'

services:
  # PostgreSQL database for local development
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: eventr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LocalStack for AWS services (S3, DynamoDB)
  localstack:
    image: localstack/localstack:2.3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-init:/docker-entrypoint-initaws.d
      - localstack-data:/tmp/localstack/data

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  postgres-data:
  localstack-data:
